# Generated by Django 4.1.7 on 2023-04-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing',
            name='date',
            field=models.DateField(verbose_name='Date as YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='time_spent',
            field=models.DurationField(verbose_name='time spent - in minutes'),
        ),
    ]
