# Generated by Django 4.1.7 on 2023-04-26 22:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_alter_timing_date_alter_timing_time_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('favorited_by', models.ManyToManyField(related_name='favorite_videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
