# Generated by Django 4.1.7 on 2023-04-27 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
    ]
