# Generated by Django 4.1.7 on 2023-04-27 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_remove_video_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='favorited_by',
        ),
        migrations.AddField(
            model_name='video',
            name='favorited_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
